default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: octo_events

test:
  <<: *default
  database: octo_events_test

production:
  <<: *default
  database: octo_events_production
  username: octo_events
  password: <%= ENV['OCTO_EVENTS_DATABASE_PASSWORD'] %>

